name: Build Web App

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
    
    - name: Setup MSBuild Path
      uses: Dana-Prajea/Setup-MSBuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.7
    
    - name: Restore NuGet Packages
      run: nuget restore SimpleFrameworkApp.sln

    - name: Build and Publish Web App
      run: msbuild SimpleFrameworkApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Upload Artifact
      uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
      with:
        name: published_webapp
        path: bin/Release/Publish
