name: Build Web App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
          
    - name: Setup MSBuild Path
      uses: Dana-Prajea/Setup-MSBuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.7
    
    - name: Restore NuGet Packages
      run: nuget restore textAction.sln

    - name: Build and Publish Web App
      run: msbuild textAction.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: bin\Release\Publish
